#!/usr/bin/env sh

# Define protected branch names (separated by space)
# PROTECTED_BRANCH_NAMES="main master"

# Extract the branch name
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Stop if the current branch is protected
if [ -n "$PROTECTED_BRANCH_NAMES" ]; then
  for PROTECTED_BRANCH_NAME in $PROTECTED_BRANCH_NAMES; do
    if [ "$BRANCH_NAME" = "$PROTECTED_BRANCH_NAME" ]; then
      echo "❌ You are on the '$BRANCH_NAME' branch. Please create a new branch for your changes."
      exit 1
    fi
  done
fi

# Fetch the current commit message
COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Regex pattern to check for a valid conventional commit (e.g. from cz)
EXISTING_PREFIX_PATTERN="^([a-z]+)(\([^)]+\))?: .+"

# Check if the commit message is already a valid conventional commit
if echo "$COMMIT_MSG" | grep -qE "$EXISTING_PREFIX_PATTERN"; then
  exit 0
fi

# Run Commitizen
exec </dev/tty && ./node_modules/.bin/git-cz --hook
